source 'https://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'thin'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass'
end

gem "pry", :group => :development

group :development, :test do
  gem 'rspec-rails'
end


gem 'hirb'
gem "awesome_print"

gem 'jquery-rails'
gem 'devise'
gem 'haml'
gem 'httparty'
gem 'rails-settings-cached'
gem 'squeel'
gem 'foreman'
gem 'rest-client'
gem 'nokogiri'

# Use the wlvalidate gem for White Label validation
gem 'wlvalidate'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
